-- Temporarily disable RLS for migration
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE widgets DISABLE ROW LEVEL SECURITY;
ALTER TABLE widget_translations DISABLE ROW LEVEL SECURITY;
ALTER TABLE widget_faqs DISABLE ROW LEVEL SECURITY;
ALTER TABLE widget_related DISABLE ROW LEVEL SECURITY;
ALTER TABLE widget_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE usage_events DISABLE ROW LEVEL SECURITY;