-- Re-enable RLS after migration
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE widgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE widget_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE widget_faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE widget_related ENABLE ROW LEVEL SECURITY;
ALTER TABLE widget_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_events ENABLE ROW LEVEL SECURITY;